### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by Caroga** [superjunky/Domoticz-Brel-Plugin#1]
Hi there!
I'm trying to find information about the brel home router and how to interface with it. 
I was wondering, besides reading your code, how I could do some stuff with this.
Where and how did you manage to get this to work, I cannot seem to find any documentation on the api of the device.

Any references or help would be very much appreciated.
Thank you in advance.

**Comment by Caroga** [comment]
Ow wow, I feel like such an idiot. It's after posting this message that I saw the pdf files in your repository. I will take a look at this.
Also, retrieving the key: does this only work in the iphone app or also android ?

**Comment by superjunky** [comment]
Yeah exactly, the docs :)
For this plugin I made use of the UDP interface since it doesn't require internet. The Restful API is fairly new, I never tested it. (While writing it comes to mind I did not even add it to the repo. Will do that right away.)

As for the key; I only was able to test it on ios, but I'm certain it works the same for Android. I recall their app was originally designed for Android.

**Comment by Caroga** [comment]
Thank you for your quick response!
I currently am unable to generate a API key on the android app. Using the Brel Home app I tried pressing quickly 5 times on the Version number on the settings page but this did not result in an key being displayed. 
I will install the app on my iPhone, see if this helps
I will check the JSON document right away.

**Comment by superjunky** [comment]
If you haven't done so, make sure you have the bridge setup with your app before retrieving the key.
I remember having some issues setting up the bridge because it needed a WIFI network dedicated for 2.4G. When you combine it with a 5G network, the hub fails to connect.

**Comment by Caroga** [comment]
I've connected succesfully with the Brel device using the brel app. I can control my devices too. The wifi is 2.4ghz indeed. 
I do see that the app differs from the documentation (connector app) where I am using the Brel Home https://play.google.com/store/apps/details?id=com.id3.icurtain.brel&hl=nl&gl=US 
Which app are you using?

**Comment by superjunky** [comment]
The Brel app. I couldn't get the connector app to work. Instead of tapping 5 times, perhaps try tapping the version number like a maniac ;)

At first I used a rather hard-coded script for sending commands to the Hub. I have added it to the docs folder in the repo. Maybe it's helpfull

**Comment by Caroga** [comment]
I will take a lookt at the script, thank you very much!
In the meantime I've bashed the version number like a maniac on steroids but still am unable to get a key from the app.
For the sake if science I've posted a screenshot from the app where I'm poking the version number at:
![image](https://user-images.githubusercontent.com/4005934/107886018-b22ce500-6efd-11eb-9350-208f9048355d.png)

I assume, since I could not find any other location displaying the version number, this is the right place. Right?

**Comment by superjunky** [comment]
Yes thats where I got it from. Check my screen.
Well... I would fire-off an email to Brel. I know for a fact the tech-person is on Android, he should be able to help you out. And if you do, please share the answer here. You got me curious
<img width="169" alt="Schermafbeelding 2021-02-14 om 19 52 15" src="https://user-images.githubusercontent.com/9337767/107886205-ab52a200-6efe-11eb-8366-569ee1ade30f.png">

**Comment by Caroga** [comment]
I see you are running version 1.1.5(3) where I have 1.1.0.0125. Maybe this could be a reason as to why it's not working. I'll try it with my iPhone too if that's possible.
Anyway I'll be contacting support yeah, maybe the tech-person over that could assist me with this. 
I thank you very much for your time and help so far!

**Comment by Caroga** [comment]
Okay I got the key from the iPhone, hooray! Still be contacting support though.
I will try (to modify) your scripts to see if I can get some stuff from the hub. I'm not a python developer but I think I'll manage. 
🎉

**Comment by Caroga** [comment]
Hey! I completely forgot closing this ticket, thanks for your help! I have succeeded creating a connection via python with the device. I have however not had the privilege to continue and finish the work. Hopefully some day soon. 
Thank you for your help, much appreciated!
