### ISSUE TITLE
Domoticz freeze after update hardware settings

### ISSUE THREAD

**Issue by Heukers** [superjunky/Domoticz-Brel-Plugin#3]
after updating the hardware settings in domoticz, i get a message that there is a problem in saving the hardware.

Domoticz loses all hardware.... But do not worry, after a reboot everything works fine and.....

The adjustment in the settings are also saved correct...

**Comment by superjunky** [comment]
I remember this behaviour but haven't seen this in a long time. You would have to turn to Domoticz rather than this python-plugin. I am currently using the latest Domoticz beta in the official Domoticz-Docker-Image.

**Comment by Heukers** [comment]
I think you are right with that tought... i use the former Jadhal plugin for synology 2020.1 and the recent update by synocommunity does not work yet..... i think the problem will be solved with a new version of domoticz. But now it can be found in the issues.... at this wonderfull plugin!

**Comment by superjunky** [comment]
Hahaha thanks,

You are on DSM right? Jadahl is not updating the packages anymore (not sure). If you can, try and switch to Docker. It truly offers many benefits.
