### ISSUE TITLE
Unable to retrieve key

### ISSUE THREAD

**Issue by jerkelens** [superjunky/Domoticz-Brel-Plugin#7]
Hi,

Not so much an issue with the plugin, but the required procedure instead. Currently with app version 1.1.2.1102 (Android), the method to retrieve the api key doesn't work anymore. This renders the plugin unusable.

**Comment by superjunky** [comment]
Can you perhaps use the support section in the Android app to ask the developer for a workaround? If you do, could you please share it here?

**Comment by superjunky** [comment]
On Android retrieve the key by tapping 5 times next to the profile picture in the Brel app.
